name: Production Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    environment: Production
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        export_type: ["interfaces", "all"]

    env:
      NPM_PACKAGE_NAME: "@defi-wonderland/canon-guard"
      EXPORT_NAME: ${{ matrix.export_type == 'interfaces' && '-interfaces' || '' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 22.17.0

      - name: Update npm
        run: npm install -g npm@11.5.2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project and generate out directory
        run: yarn build

      - name: Export Solidity - Export Type ${{ matrix.export_type }}
        uses: defi-wonderland/solidity-exporter-action@v2.2.0
        with:
          package_name: ${{ env.NPM_PACKAGE_NAME }}
          out: "out"
          interfaces: "src/interfaces"
          contracts: "src/contracts"
          export_type: "${{ matrix.export_type }}"

      - name: Publish to NPM - Export Type ${{ matrix.export_type }}
        run: cd export/${{ env.NPM_PACKAGE_NAME }}${{ env.EXPORT_NAME }} && npm publish --access public --tag latest
